import type { PracticeSet } from './types';

export const INITIAL_MOCK_PRACTICE_SETS: PracticeSet[] = [
  {
    id: 'practice-1',
    teacherId: 'teacher-1',
    classId: 'class-1',
    className: 'Lớp 4A',
    subject: 'Toán',
    grade: '4',
    title: 'Củng cố phép chia số có hai chữ số',
    type: 'REMEDIATION',
    status: 'ASSIGNED',
    dueAt: '2026-10-10T23:59:59.000Z',
    allowRetry: true,
    maxAttempts: 1,
    feedbackMode: 'AFTER_FINISH',
    createdAt: '2026-10-06T10:00:00.000Z',
    assignedAt: '2026-10-06T10:15:00.000Z',
    createdBy: 'Thầy Hương',
    source: 'HISTORY_REMEDIATION',
    questions: [
      {
        id: 'pq-1',
        type: 'MULTIPLE_CHOICE',
        content: 'Thực hiện phép tính chia: 288 : 12 = ?',
        options: ['22', '24', '26', '28'],
        correctAnswer: 'B',
        explanation: '288 : 12 = 24.',
        difficulty: 'UNDERSTANDING',
      },
      {
        id: 'pq-2',
        type: 'MULTIPLE_CHOICE',
        content: 'Một thùng đựng 450 quyển vở được chia đều cho 15 lớp. Hỏi mỗi lớp nhận bao nhiêu quyển?',
        options: ['25 quyển', '30 quyển', '35 quyển', '40 quyển'],
        correctAnswer: 'B',
        explanation: '450 : 15 = 30 quyển.',
        difficulty: 'APPLICATION',
      },
      {
        id: 'pq-3',
        type: 'TRUE_FALSE',
        content: 'Số 360 chia hết cho cả 2, 3 và 5.',
        correctAnswer: 'Đúng',
        explanation: '360 tận cùng bằng 0 (chia hết cho 2 và 5), tổng chữ số 3+6+0=9 (chia hết cho 3).',
        difficulty: 'KNOWLEDGE',
      },
      {
        id: 'pq-4',
        type: 'SHORT_ANSWER',
        content: 'Tính thương của 625 và 25.',
        correctAnswer: '25',
        explanation: '625 : 25 = 25.',
        difficulty: 'UNDERSTANDING',
      },
    ],
    assignments: {
      'std-3': {
        studentId: 'std-3',
        studentName: 'Lê Thu Cúc',
        assignedAt: '2026-10-06T10:15:00.000Z',
        status: 'COMPLETED',
        startedAt: '2026-10-06T14:20:00.000Z',
        completedAt: '2026-10-06T14:30:00.000Z',
        attemptCount: 1,
        score: 75,
        correctCount: 3,
        totalQuestions: 4,
      },
      'std-4': {
        studentId: 'std-4',
        studentName: 'Phạm Đức Duy',
        assignedAt: '2026-10-06T10:15:00.000Z',
        status: 'IN_PROGRESS',
        startedAt: '2026-10-06T16:00:00.000Z',
        attemptCount: 1,
      },
      'std-1': {
        studentId: 'std-1',
        studentName: 'Nguyễn Minh Anh',
        assignedAt: '2026-10-06T10:15:00.000Z',
        status: 'NOT_STARTED',
        attemptCount: 0,
      },
    },
    responses: {
      'pq-1_std-3': {
        id: 'pq-1_std-3',
        questionId: 'pq-1',
        studentId: 'std-3',
        answer: 'B',
        submittedAt: '2026-10-06T14:22:00.000Z',
        attemptNumber: 1,
        isCorrect: true,
      },
      'pq-2_std-3': {
        id: 'pq-2_std-3',
        questionId: 'pq-2',
        studentId: 'std-3',
        answer: 'B',
        submittedAt: '2026-10-06T14:25:00.000Z',
        attemptNumber: 1,
        isCorrect: true,
      },
      'pq-3_std-3': {
        id: 'pq-3_std-3',
        questionId: 'pq-3',
        studentId: 'std-3',
        answer: 'Đúng',
        submittedAt: '2026-10-06T14:27:00.000Z',
        attemptNumber: 1,
        isCorrect: true,
      },
      'pq-4_std-3': {
        id: 'pq-4_std-3',
        questionId: 'pq-4',
        studentId: 'std-3',
        answer: '20',
        submittedAt: '2026-10-06T14:29:00.000Z',
        attemptNumber: 1,
        isCorrect: false,
      },
    },
    archived: false,
  },
  {
    id: 'practice-2',
    teacherId: 'teacher-1',
    classId: 'class-1',
    className: 'Lớp 4A',
    subject: 'Khoa học',
    grade: '4',
    title: 'Luyện tập Nước và các thể của nước',
    type: 'PRACTICE',
    status: 'READY',
    dueAt: '2026-10-15T23:59:59.000Z',
    allowRetry: false,
    maxAttempts: 1,
    feedbackMode: 'AFTER_FINISH',
    createdAt: '2026-10-05T09:00:00.000Z',
    createdBy: 'Thầy Hương',
    source: 'QUESTION_BANK',
    questions: [
      {
        id: 'pq-21',
        type: 'MULTIPLE_CHOICE',
        content: 'Nước tồn tại ở mấy thể chính?',
        options: ['2 thể', '3 thể', '4 thể', '5 thể'],
        correctAnswer: 'B',
        explanation: '3 thể: Thể lỏng, thể khí và thể rắn.',
        difficulty: 'KNOWLEDGE',
      },
    ],
    assignments: {},
    responses: {},
    archived: false,
  },
];
